# -*- coding: utf-8 -*-
"""Caesar Cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaonOjqd7Vwato9XL-036wztXq0rsYRV
"""

key = int(input("Key: "))

p = input("plaintext: ")
new = ""
for i in p:
    if i.isalpha():
        if i.isupper():
            new+=chr(((ord(i)+key)%65)%26+65)
        else:
            new+=chr(((ord(i)+key)%97)%26+97)
    else:
        new+=i

print("ciphertext:",new)

