# -*- coding: utf-8 -*-
"""Substitution Cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaonOjqd7Vwato9XL-036wztXq0rsYRV
"""

from collections import Counter

while True:
    try:
        key = input("Key: ")
        if len(key)==26 and key.isalpha() and len(Counter(key))==len(key):
            break
    except:
        continue
    else:
        pass

p = input("plaintext: ")
new = ""
for i in p:
    if i.isalpha():
        if i.isupper():
            new+=key[ord(i)-65].upper()
        else:
            new+=key[ord(i)-97].lower()
    else:
        new+=i

print("ciphertext:",new)